### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Sajo8** [krruzic/BPIDM#4]
Downloaded zip, extracted .exe to desktop, crashed on opening. Extracted folder to desktop, crashed on opening. I was interested in seeing how it worked, is this only available on the restaurants' devices?

**Comment by krruzic** [comment]
Hey Sajo, I know. The server with the images and menu json is down now. I can maybe find that stuff and rehost it but for now I guess the app is unusable. It doesn't really do anything anyway tho

**Comment by Sajo8** [comment]
:( Okay
